version: '3.7'

services:
  django:
    build: ./django/
    restart: always
    env_file:
      - ./.env
      - ./.env_db
    ports:
      - 8000:8000
    volumes:
      - ./django/air_base/:/app/django/air_base/
      - ./frontend/build/:/app/frontend/build/
      - ./logs/:/app/django/logs/
    depends_on:
      - frontend
      - db
    command: bash -c "./init/django_setup.sh && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend/
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./frontend/build/:/app/frontend/build/
      - ./frontend/src/:/app/frontend/src/
    command: npm run build:watch

  db:
    build: ./postgres/
    restart: always
    env_file:
      - ./.env
      - ./.env_db
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
