version: '3.7'

services:
  webapp:
    build: ./
    restart: always
    env_file:
      - ./.env
      - ./.env_db
    ports:
      - 8000:8000
    volumes:
      - ./air_base/:/app/air_base/
      - ./frontend/build/:/app/frontend/build/
      - ./logs/:/app/logs/
    depends_on:
      - frontend
      - db

  frontend:
    build: ./frontend/
    env_file:
      - ./.env
    volumes:
      - ./frontend/build/:/app/frontend/build/
      - ./frontend/src/:/app/frontend/src/
    command: npm run build:watch

  db:
    build: ./postgres/
    restart: always
    env_file:
      - ./.env
      - ./.env_db
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
