version: '3.7'

services:
  django:
    volumes:
      - django:/app/django/air_base/
      - frontend:/app/frontend/build/
    command: bash -c "./init/django_setup.sh && gunicorn air_base.wsgi -b 0.0.0.0:8000"

  frontend:
    restart: 'no'
    volumes:
      - frontend:/app/frontend/build/
    command: npm run build

  nginx:
    build: ./nginx/
    restart: always
    env_file:
      - ./.env
    ports:
      - 80:80
    volumes:
      - frontend:/app/frontend/build/
      - ./logs/:/app/logs/
    depends_on:
      - django
    command: nginx -g "daemon off;"

volumes:
  django:
  frontend:
